### ISSUE TITLE
Sending mail from admin is not caught

### ISSUE THREAD

**Issue by Tusky** [scuml/django-mail-panel#10]
Like sending mails from an admin action. Console backend displays sent mails, but mail panel lists none.

**Comment by Tusky** [comment]
It was caused by DummyCache, it needs valid caching to work.

**Comment by joelburton** [comment]
@scuml : It would be helpful to make a note about DummyCache causing this not to work in your installation instructions. I had the same problem and figured it out after a bit of playing around. I could imagine other people having this same issues.

Thanks, and thanks for this product!

**Comment by scuml** [comment]
Good idea @joelburton

**Comment by scuml** [comment]
Fixed in 3.2.5.

Mail Panel switches over to LocMemCache if DummyCache is set. 
Added additional documentation on cache use in README.
