### ISSUE TITLE
Does not function in DJDT v3.1

### ISSUE THREAD

**Issue by mmangione** [scuml/django-mail-panel#17]
This plugin fails for Django Debug Toolbar v3.1. Window opens, but the message list is no longer clickable and the content area never displays. I can confirm it is working in 2.2 for us.

**Comment by scuml** [comment]
I'll check it out.  Thanks.

**Comment by scuml** [comment]
Django Mail Panel 3.1 has been released and should be compatible with Debug Toolbar 3.1.  Please download, test, and feel free to close the issue if it works.

`pip install django-mail-panel==3.1`

**Comment by mmangione** [comment]
Thank you! Checking it now. :)

**Comment by mmangione** [comment]
@scuml Confirmed! I spent 3 hours trying to fix this myself before I submitted this issue. Thank you!

**Comment by scuml** [comment]
Glad it worked.  Thanks for trying your hand at a fix first!  (It ended up being that javascript wasn't loaded in the latest version when used in a <script> tag.  So any javascript files now had to be specified in the panel python view.  Simple fix, but tough just to diagnose what's going on.)

**Comment by jasperhartong** [comment]
Seems that the latest version (3.2.2) has the same issue again: the message list is no longer clickable and the content area never displays. Installed 3.1 for now, which does work nicely with django-debug-toolbar==3.2.

Not sure if this warranted a new issue or not :)

Thanks for this plugin!

**Comment by scuml** [comment]
@jasperhartong This was fixed in 3.2.3.  Please try that.

**Comment by jasperhartong** [comment]
@scuml Wow, that was fast. Just tried 3.2.3 and it's indeed fixed. Thanks!
