### ISSUE TITLE
Support for Python3

### ISSUE THREAD

**Issue by dethos** [scuml/django-mail-panel#2]
After trying to add this package to one of my projects, I've got this error:

```
File ".../site-packages/mail_panel/backend.py", line 27, in send_messages
    message.id = uuid4().get_hex()
AttributeError: 'UUID' object has no attribute 'get_hex'
```

It seems this package doesn't yet support python3. Is there any plan to make it compatible in the foreseeable future?

**Comment by scuml** [comment]
Thanks for the info.  Yeah...unit tests are a bit sparse at this time and missed this one.  Upped 1.0.4 to PyPI with the fix - please let me know if there's any other errors.

**Comment by dethos** [comment]
I still get the same error on the same line, this might be because there is a catch in the code for a `ValueError` while the one that I'm having is an `AttributeError`.

**Comment by scuml** [comment]
That's it - pushed the latest to PyPi.  Thanks.
