### ISSUE TITLE
'EmailMessage' object has no attribute 'alternatives'

### ISSUE THREAD

**Issue by surfer190** [scuml/django-mail-panel#32]
Django Version: 3.2.11
django-mail-panel==3.2.6
django-debug-toolbar==3.2.4

`Exception Value: 'EmailMessage' object has no attribute 'alternatives'`

I am using the [django-tempalted-email 3.0.0 package](https://pypi.org/project/django-templated-email/) to send an email:

    send_templated_mail(...)

I attempted to fix it with:

        try:
            alternatives = message.alternatives
        except AttributeError:
            alternatives = None

        super(MailToolbarBackendEmail, self).__init__(
            subject=message.subject,
            to=message.to,
            cc=message.cc,
            bcc=message.bcc,
            reply_to=message.reply_to,
            from_email=message.from_email,
            body=message.body,
            alternatives=alternatives,
            headers=message.extra_headers,
        )

**Comment by KicksTV** [comment]
Any chance we can get this change implemented? I am hitting the same bug.

**Comment by scuml** [comment]
Sure thing.  Available in django-mail-panel 4.0.4.  

Able to deliver results faster if you submit a PR.
