### ISSUE TITLE
Trove classifiers not added on PyPI

### ISSUE THREAD

**Issue by arshsingh** [scuml/django-mail-panel#4]
Even though `classifiers` are listed in `setup.py`, they're not there on PyPI: https://pypi.python.org/pypi/django-mail-panel

Maybe we should try uploading with a newer version of setuptools ?

(The python 3 classifier is required to list the package in the "Python 3" list on PyPI. Also this tool: https://github.com/brettcannon/caniusepython3 uses the classifier to check for python 3 support for a package)

**Comment by scuml** [comment]
Thanks @arshsingh!
