### ISSUE TITLE
HTML-only emails are displayed incorrectly

### ISSUE THREAD

**Issue by jonashaag** [scuml/django-mail-panel#5]
The code assumes that a text/plain alternative is always available. If only HTML alternative is available, the mail display view breaks.

**Comment by jonashaag** [comment]
Is this project still maintained?

**Comment by scuml** [comment]
Thanks for the report.  Swamped with work, but will try to look at it in the next few days.

**Comment by jonashaag** [comment]
If you can give a few pointers where to look I can try to come up with a patch.

**Comment by scuml** [comment]
Could not replicate this.  Using django's tutorial:
`from django.core.mail import EmailMultiAlternatives
subject, from_email, to = 'hello', 'from@example.com', 'to@example.com'
html_content = '<p>This is an <strong>important</strong> message.</p>'
msg = EmailMultiAlternatives(subject, '', from_email, [to])
msg.attach_alternative(html_content, "text/html")
msg.send()`

Results in the expected:
![screen shot 2017-12-17 at 8 33 27 am](https://user-images.githubusercontent.com/1790447/34079945-07e5b842-e305-11e7-88a5-919464477808.png)

**Comment by jonashaag** [comment]
Your message has an empty text/plain message. It doesn't work if you have no text/plain message at all:

```py
from django.core.mail import EmailMultiAlternatives
subject, from_email, to = 'hello', 'from@example.com', 'to@example.com'
html_content = '<p>This is an <strong>important</strong> message.</p>'
msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
msg.content_subtype = 'html'
msg.send()
```

**Comment by hugotacito** [comment]
I believe I fixed this in this PR: https://github.com/scuml/django-mail-panel/pull/6

**Comment by scuml** [comment]
Patch will be out on Pypi in the next few days.   Will close when updated.  Thanks @hugotacito

**Comment by scuml** [comment]
Deployed as 1.2.0 and pushed to PyPI.
May need to force an update with:
`pip install django-mail-panel==1.2` or 
`pipenv install django-mail-panel==1.2 --dev`
